

@Library("shared-libs@master") _

pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
            gitCheckout(
                branch: "master",
                url: "https://github.com/rsravanam/python-learn.git"
            )

            slackAlert(
                channel: '#devops',
                status: 'SHARED LIB TEST'
                environment: 'test'
            )
            }
    }
    }
}