
pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            sl = load 'jenkins-shared-libs/vars/gitCheckout.groovy'
            steps {
            sl.gitCheckout(
                branch: "master",
                url: "https://github.com/rsravanam/python-learn.git"
            )
            }
    }
    }
}