@SharedLibrary('jenkins-shared-libs') _

pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
            gitCheckout(
                branch: "master",
                url: "https://github.com/rsravanam/python-learn.git"
            )
            }
    }
    }
}