apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: nginx
    server: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvolume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: hostvolume
        hostPath:
          path: /home/kuber/vol
