apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-host-volume-practice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: hostvol
              mountPath: "/usr/share/nginx/html"

