apiVersion: v1
kind: Service
metadata:
  name: webserver-host-volume-practice
  labels:
    app: webserver
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: webserver
