#This playbook deploys a simple standalone Tomcat 7 server.
---

#- hosts: "{{ my_hosts | default('tomcat-server') }}"
- hosts: my_hosts
  remote_user: centos
  become: yes
  become_method: sudo

  roles:
    - zagent
