---
- name: install nginx latest version
  apt:
    name: nginx
    state: latest

- name: write the config file
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify:
  - restart nginx

- name: ensure nginx is running
  service:
    name: nginx
    state: started
